#
# This is the cluster configuration.  As guidance, the environment variables
# set within this file should be ones that do not change regardless where
# this cluster is run and what job it is working on.  
#
version: '3'
services:

  # Sidecar logger using fluentd to aggregate logs from all containers, store them to S3
  logger:
    image: dr-train-poc-redis:latest
    container_name: logger
    build:
      context: ./container
      dockerfile: Dockerfile.logger
    ports:
      - "24224:24224"
    volumes:
#     - ./container/fluent.conf:/fluentd/etc/fluent.conf
    environment:
      LOGGER_S3_DESTINATION_PATH:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      AWS_ENDPOINT_URL:
      AWS_DEFAULT_REGION:

  # Redis for local comms of graph inputs between rollout and training workers
  redis:
    image: dr-train-poc-redis:latest
    container_name: redis
    expose:
      - 6379
    command: /usr/local/etc/redis.conf --loglevel notice
    volumes:
#     - ./container/redis.conf:/usr/local/etc/redis.conf

  # ROS + Gazebo + Coach rollout worker
  dr-simulation:
    image: dr-train-poc-simulation:latest
    build:
      context: .
      dockerfile: ./container/Dockerfile
    # Allow external connections to gzserver
    ports:
      - 11345:11345
    container_name: dr-simulation
#   healthcheck:
#     test: '/home/robomaker/simulation-health.sh'
    # For easy debugging, we can map the local files over the container
    volumes:
      - ./patch/opt/install/deepracer_simulation_environment/share/deepracer_simulation_environment/launch/distributed_training.launch:/home/robomaker/workspace/bundle-store/deepracer-simapp/opt/install/deepracer_simulation_environment/share/deepracer_simulation_environment/launch/distributed_training.launch
      - ./patch/opt/install/deepracer_simulation_environment/share/deepracer_simulation_environment/meshes/Canada_Training/textures/Canada_track_revir_U_01.png:/home/robomaker/workspace/bundle-store/deepracer-simapp/opt/install/deepracer_simulation_environment/share/deepracer_simulation_environment/meshes/Canada_Training/textures/Canada_track_revir_U_01.png
      - ./patch/opt/install/deepracer_simulation_environment/share/deepracer_simulation_environment/meshes/Canada_Training/textures/Canada_track_revir_T_01.png:/home/robomaker/workspace/bundle-store/deepracer-simapp/opt/install/deepracer_simulation_environment/share/deepracer_simulation_environment/meshes/Canada_Training/textures/Canada_track_revir_T_01.png
#     - ./patch/opt/install/deepracer_simulation_environment/share/deepracer_simulation_environment/models/Canada_Training/Canada_Training_model.sdf:/home/robomaker/workspace/bundle-store/deepracer-simapp/opt/install/deepracer_simulation_environment/share/deepracer_simulation_environment/models/Canada_Training/Canada_Training_model.sdf
#      - ./patch/opt/install/deepracer_simulation_environment/share/deepracer_simulation_environment/worlds/Canada_Training.world:/home/robomaker/workspace/bundle-store/deepracer-simapp/opt/install/deepracer_simulation_environment/share/deepracer_simulation_environment/worlds/Canada_training.world
      - ./patch/opt/install/sagemaker_rl_agent/lib/python3.5/site-packages/markov:/home/robomaker/workspace/bundle-store/deepracer-simapp/opt/install/sagemaker_rl_agent/lib/python3.5/site-packages/markov
#     - ./container/entry_script2.sh:/home/robomaker/entry_script2.sh
#     - ./container/snapshots.sh:/home/robomaker/snapshots.sh
#     - ./container/streamer.sh:/home/robomaker/streamer.sh
        # Map experiment folder for tensorboard and coach gif/mp4 dumps
#     - ./experiment:/opt/ml/model
#     - /tmp/.X11-unix:/tmp/.X11-unix
    command: ['/home/robomaker/entry_script2.sh stdbuf -oL -eL roslaunch deepracer_simulation_environment ${LAUNCH_FILE}']
    logging:
      driver: fluentd
    depends_on:
      - logger
      - redis
    environment:
      AWS_ACCESS_KEY_ID: 
      AWS_SECRET_ACCESS_KEY: 
      AWS_ENDPOINT_URL: 
      AWS_ROBOMAKER_SIMULATION_JOB_ARN:
      AWS_ROBOMAKER_SIMULATION_JOB_ID:
      AWS_ROBOMAKER_SIMULATION_RUN_ID:
      AWS_ROBOMAKER_SIMULATION_APPLICATION_SETUP:
      APP_REGION:
      KINESIS_VIDEO_STREAM_NAME:
      NUMBER_OF_TRIALS:
      NUMBER_OF_EPISODES:
      WORLD_NAME:
      ALTERNATE_DRIVING_DIRECTION:
      TARGET_REWARD_SCORE:
      METRIC_NAME:
      METRIC_NAMESPACE:
      METRICS_S3_BUCKET:
      METRICS_S3_OBJECT_KEY:
      MODEL_METADATA_FILE_S3_KEY:
      REWARD_FILE_S3_KEY:
      MODEL_S3_BUCKET:
      MODEL_S3_PREFIX:
      ROBOMAKER_SIMULATION_JOB_ACCOUNT_ID:
      SAGEMAKER_SHARED_S3_BUCKET:
      SAGEMAKER_SHARED_S3_PREFIX:
      TRAINING_JOB_ARN:
      NODE_TYPE: SIMULATION_WORKER
      REDIS_HOST: redis
      MAX_JOB_DURATION:
      ROBOMAKER_ROS_MASTER_URI:
      ROBOMAKER_GAZEBO_MASTER_URI:
      # The display here is specifically set for the privileged GPU talking through a unix socket
      DISPLAY: :0
      SM_TRAINING_ENV:
      CHANGE_START_POSITION:
      START_POSITION:

  # Training worker, currently same container image as dr-simulation
  dr-training:
    image: deepracer-cuda
    build:
      context: .
      dockerfile: ./container/Dockerfile.cuda
    # For easy debugging, we can map the local files over the container
    volumes: 
      - ../patch/opt/install/sagemaker_rl_agent/lib/python3.5/site-packages/markov:/home/robomaker/workspace/bundle-store/deepracer-simapp/opt/install/sagemaker_rl_agent/lib/python3.5/site-packages/markov
#   runtime: nvidia
    logging:
      driver: fluentd
    # tensorboard
    ports:
      - 6006:6006
#   stdin_open: true
    tty: true
    container_name: dr-training
    command: ['python3 -m markov.training_worker ${TRAINING_WORKER_ARGS}']
    depends_on:
      - logger
      - redis
    environment:
      NVIDIA_VISIBLE_DEVICES: 0
      AWS_ACCESS_KEY_ID: 
      AWS_SECRET_ACCESS_KEY: 
      AWS_ENDPOINT_URL: 
      AWS_ROBOMAKER_SIMULATION_JOB_ARN:
      AWS_ROBOMAKER_SIMULATION_JOB_ID:
      AWS_ROBOMAKER_SIMULATION_RUN_ID:
      AWS_ROBOMAKER_SIMULATION_APPLICATION_SETUP:
      APP_REGION:
      KINESIS_VIDEO_STREAM_NAME:
      NUMBER_OF_TRIALS:
      NUMBER_OF_EPISODES:
      WORLD_NAME:
      ALTERNATE_DRIVING_DIRECTION:
      TARGET_REWARD_SCORE:
      METRIC_NAME:
      METRIC_NAMESPACE:
      METRICS_S3_BUCKET:
      METRICS_S3_OBJECT_KEY:
      MODEL_METADATA_FILE_S3_KEY:
      REWARD_FILE_S3_KEY:
      MODEL_S3_BUCKET:
      MODEL_S3_PREFIX:
      ROBOMAKER_SIMULATION_JOB_ACCOUNT_ID:
      SAGEMAKER_SHARED_S3_BUCKET:
      SAGEMAKER_SHARED_S3_PREFIX:
      TRAINING_JOB_ARN:
      NODE_TYPE: SAGEMAKER_TRAINING_WORKER
      REDIS_HOST: redis
      MAX_JOB_DURATION:
      ROBOMAKER_ROS_MASTER_URI:
      ROBOMAKER_GAZEBO_MASTER_URI:
      SM_TRAINING_ENV:
